-- ════════════════════════════════════════════════════════════════════
--  GCIP — seed: WC2026 teams + players
--  Extracted from SquadLists-English.pdf (48 teams x 26 players)
--  Run AFTER 01_schema.sql. Idempotent (safe to re-run).
-- ════════════════════════════════════════════════════════════════════

insert into public.teams (code, name) values
  ('ALG', 'Algeria'),
  ('ARG', 'Argentina'),
  ('AUS', 'Australia'),
  ('AUT', 'Austria'),
  ('BEL', 'Belgium'),
  ('BIH', 'Bosnia And Herzegovina'),
  ('BRA', 'Brazil'),
  ('CPV', 'Cabo Verde'),
  ('CAN', 'Canada'),
  ('COL', 'Colombia'),
  ('COD', 'Congo DR'),
  ('CRO', 'Croatia'),
  ('CUW', 'Curaçao'),
  ('CZE', 'Czechia'),
  ('CIV', 'Côte D''Ivoire'),
  ('ECU', 'Ecuador'),
  ('EGY', 'Egypt'),
  ('ENG', 'England'),
  ('FRA', 'France'),
  ('GER', 'Germany'),
  ('GHA', 'Ghana'),
  ('HAI', 'Haiti'),
  ('IRN', 'IR Iran'),
  ('IRQ', 'Iraq'),
  ('JPN', 'Japan'),
  ('JOR', 'Jordan'),
  ('KOR', 'Korea Republic'),
  ('MEX', 'Mexico'),
  ('MAR', 'Morocco'),
  ('NED', 'Netherlands'),
  ('NZL', 'New Zealand'),
  ('NOR', 'Norway'),
  ('PAN', 'Panama'),
  ('PAR', 'Paraguay'),
  ('POR', 'Portugal'),
  ('QAT', 'Qatar'),
  ('KSA', 'Saudi Arabia'),
  ('SCO', 'Scotland'),
  ('SEN', 'Senegal'),
  ('RSA', 'South Africa'),
  ('ESP', 'Spain'),
  ('SWE', 'Sweden'),
  ('SUI', 'Switzerland'),
  ('TUN', 'Tunisia'),
  ('TUR', 'Türkiye'),
  ('USA', 'USA'),
  ('URU', 'Uruguay'),
  ('UZB', 'Uzbekistan')
on conflict (code) do update set name = excluded.name;

insert into public.players (team_code, shirt_number, position, name) values
  ('ALG', 1, 'GK', 'MASTIL'),
  ('ALG', 2, 'DF', 'MANDI'),
  ('ALG', 3, 'DF', 'ABADA'),
  ('ALG', 4, 'DF', 'TOUGAI'),
  ('ALG', 5, 'DF', 'BELAID'),
  ('ALG', 6, 'MF', 'ZERROUKI'),
  ('ALG', 7, 'FW', 'MAHREZ'),
  ('ALG', 8, 'MF', 'AOUAR'),
  ('ALG', 9, 'FW', 'GOUIRI'),
  ('ALG', 10, 'MF', 'CHAIBI'),
  ('ALG', 11, 'FW', 'HADJ MOUSSA'),
  ('ALG', 12, 'FW', 'BENBOUALI'),
  ('ALG', 13, 'DF', 'HADJAM'),
  ('ALG', 14, 'MF', 'BOUDAOUI'),
  ('ALG', 15, 'DF', 'AIT NOURI'),
  ('ALG', 16, 'GK', 'BENBOT'),
  ('ALG', 17, 'DF', 'BELGHALI'),
  ('ALG', 18, 'FW', 'AMOURA'),
  ('ALG', 19, 'MF', 'BENTALEB'),
  ('ALG', 20, 'FW', 'BOULBINA'),
  ('ALG', 21, 'DF', 'BENSEBAINI'),
  ('ALG', 22, 'MF', 'MAZA'),
  ('ALG', 23, 'GK', 'ZIDANE'),
  ('ALG', 24, 'MF', 'TITRAOUI'),
  ('ALG', 25, 'FW', 'GHEDJEMIS'),
  ('ALG', 26, 'DF', 'CHERGUI'),
  ('ARG', 1, 'GK', 'MUSSO'),
  ('ARG', 2, 'DF', 'SENESI'),
  ('ARG', 3, 'DF', 'TAGLIAFICO'),
  ('ARG', 4, 'DF', 'MONTIEL'),
  ('ARG', 5, 'MF', 'PAREDES'),
  ('ARG', 6, 'DF', 'MARTÍNEZ'),
  ('ARG', 7, 'MF', 'DE PAUL'),
  ('ARG', 8, 'MF', 'BARCO'),
  ('ARG', 9, 'FW', 'J. ALVAREZ'),
  ('ARG', 10, 'FW', 'MESSI'),
  ('ARG', 11, 'MF', 'LO CELSO'),
  ('ARG', 12, 'GK', 'RULLI'),
  ('ARG', 13, 'DF', 'ROMERO'),
  ('ARG', 14, 'MF', 'PALACIOS'),
  ('ARG', 15, 'MF', 'N. GONZALEZ'),
  ('ARG', 16, 'FW', 'ALMADA'),
  ('ARG', 17, 'FW', 'SIMEONE'),
  ('ARG', 18, 'FW', 'NICO PAZ'),
  ('ARG', 19, 'DF', 'OTAMENDI'),
  ('ARG', 20, 'MF', 'MAC ALLISTER'),
  ('ARG', 21, 'FW', 'LOPEZ'),
  ('ARG', 22, 'FW', 'L. MARTINEZ'),
  ('ARG', 23, 'GK', 'E. MARTINEZ'),
  ('ARG', 24, 'MF', 'E. FERNANDEZ'),
  ('ARG', 25, 'DF', 'MEDINA'),
  ('ARG', 26, 'DF', 'MOLINA'),
  ('AUS', 1, 'GK', 'RYAN'),
  ('AUS', 2, 'DF', 'DEGENEK'),
  ('AUS', 3, 'DF', 'CIRCATI'),
  ('AUS', 4, 'DF', 'ITALIANO'),
  ('AUS', 5, 'DF', 'BOS'),
  ('AUS', 6, 'DF', 'GERIA'),
  ('AUS', 7, 'FW', 'LECKIE'),
  ('AUS', 8, 'MF', 'METCALFE'),
  ('AUS', 9, 'FW', 'TOURE'),
  ('AUS', 10, 'FW', 'HRUSTIC'),
  ('AUS', 11, 'FW', 'MABIL'),
  ('AUS', 12, 'GK', 'IZZO'),
  ('AUS', 13, 'MF', 'O''NEILL'),
  ('AUS', 14, 'MF', 'DEVLIN'),
  ('AUS', 15, 'DF', 'TREWIN'),
  ('AUS', 16, 'DF', 'BEHICH'),
  ('AUS', 17, 'FW', 'IRANKUNDA'),
  ('AUS', 18, 'GK', 'BEACH'),
  ('AUS', 19, 'DF', 'SOUTTAR'),
  ('AUS', 20, 'FW', 'VOLPATO'),
  ('AUS', 21, 'DF', 'BURGESS'),
  ('AUS', 22, 'MF', 'IRVINE'),
  ('AUS', 23, 'FW', 'VELUPILLAY'),
  ('AUS', 24, 'MF', 'OKON-ENGSTLER'),
  ('AUS', 25, 'DF', 'HERRINGTON'),
  ('AUS', 26, 'FW', 'YENGI'),
  ('AUT', 1, 'GK', 'SCHLAGER'),
  ('AUT', 2, 'DF', 'AFFENGRUBER'),
  ('AUT', 3, 'DF', 'DANSO'),
  ('AUT', 4, 'MF', 'XAVER'),
  ('AUT', 5, 'DF', 'POSCH'),
  ('AUT', 6, 'MF', 'SEIWALD'),
  ('AUT', 7, 'FW', 'ARNAUTOVIC'),
  ('AUT', 8, 'DF', 'ALABA'),
  ('AUT', 9, 'MF', 'SABITZER'),
  ('AUT', 10, 'MF', 'GRILLITSCH'),
  ('AUT', 11, 'FW', 'GREGORITSCH'),
  ('AUT', 12, 'GK', 'WIEGELE'),
  ('AUT', 13, 'GK', 'PENTZ'),
  ('AUT', 14, 'FW', 'KALAJDZIC'),
  ('AUT', 15, 'DF', 'LIENHART'),
  ('AUT', 16, 'DF', 'MWENE'),
  ('AUT', 17, 'MF', 'CHUKWUEMEKA'),
  ('AUT', 18, 'MF', 'SCHMID'),
  ('AUT', 19, 'MF', 'LJUBICIC'),
  ('AUT', 20, 'MF', 'LAIMER'),
  ('AUT', 21, 'FW', 'WIMMER'),
  ('AUT', 22, 'MF', 'PRASS'),
  ('AUT', 23, 'DF', 'FRIEDL'),
  ('AUT', 24, 'MF', 'WANNER'),
  ('AUT', 25, 'DF', 'SVOBODA'),
  ('AUT', 26, 'MF', 'SCHÖPF'),
  ('BEL', 1, 'GK', 'COURTOIS'),
  ('BEL', 2, 'DF', 'DEBAST'),
  ('BEL', 3, 'DF', 'THEATE'),
  ('BEL', 4, 'DF', 'MECHELE'),
  ('BEL', 5, 'DF', 'DE CUYPER'),
  ('BEL', 6, 'MF', 'WITSEL'),
  ('BEL', 7, 'MF', 'DE BRUYNE'),
  ('BEL', 8, 'MF', 'TIELEMANS'),
  ('BEL', 9, 'FW', 'LUKAKU'),
  ('BEL', 10, 'FW', 'TROSSARD'),
  ('BEL', 11, 'FW', 'DOKU'),
  ('BEL', 12, 'GK', 'LAMMENS'),
  ('BEL', 13, 'GK', 'PENDERS'),
  ('BEL', 14, 'FW', 'LUKEBAKIO'),
  ('BEL', 15, 'DF', 'MEUNIER'),
  ('BEL', 16, 'DF', 'DE WINTER'),
  ('BEL', 17, 'FW', 'DE KETELAERE'),
  ('BEL', 18, 'DF', 'SEYS'),
  ('BEL', 19, 'MF', 'MOREIRA JR'),
  ('BEL', 20, 'MF', 'VANAKEN'),
  ('BEL', 21, 'DF', 'CASTAGNE'),
  ('BEL', 22, 'MF', 'SAELEMAEKERS'),
  ('BEL', 23, 'MF', 'RASKIN'),
  ('BEL', 24, 'MF', 'ONANA'),
  ('BEL', 25, 'DF', 'NGOY'),
  ('BEL', 26, 'FW', 'FERNANDEZ-PARDO'),
  ('BIH', 1, 'GK', 'VASILJ'),
  ('BIH', 2, 'DF', 'MUJAKIĆ'),
  ('BIH', 3, 'DF', 'HADŽIKADUNIĆ'),
  ('BIH', 4, 'DF', 'MUHAREMOVIĆ'),
  ('BIH', 5, 'DF', 'KOLAŠINAC'),
  ('BIH', 6, 'MF', 'TAHIROVIĆ'),
  ('BIH', 7, 'DF', 'DEDIĆ'),
  ('BIH', 8, 'MF', 'GIGOVIĆ'),
  ('BIH', 9, 'FW', 'BAŽDAR'),
  ('BIH', 10, 'FW', 'DEMIROVIĆ'),
  ('BIH', 11, 'FW', 'DŽEKO'),
  ('BIH', 12, 'GK', 'JURKAS'),
  ('BIH', 13, 'MF', 'BAŠIĆ'),
  ('BIH', 14, 'MF', 'ŠUNJIĆ'),
  ('BIH', 15, 'MF', 'MEMIĆ'),
  ('BIH', 16, 'MF', 'HADŽIAHMETOVIĆ'),
  ('BIH', 17, 'MF', 'BURNIĆ'),
  ('BIH', 18, 'DF', 'KATIĆ'),
  ('BIH', 19, 'FW', 'ALAJBEGOVIĆ'),
  ('BIH', 20, 'FW', 'BAJRAKTAREVIĆ'),
  ('BIH', 21, 'DF', 'RADELJIĆ'),
  ('BIH', 22, 'GK', 'ZLOMISLIĆ'),
  ('BIH', 23, 'FW', 'TABAKOVIĆ'),
  ('BIH', 24, 'DF', 'MALIĆ'),
  ('BIH', 25, 'FW', 'LUKIĆ'),
  ('BIH', 26, 'MF', 'MAHMIĆ'),
  ('BRA', 1, 'GK', 'A. BECKER'),
  ('BRA', 2, 'MF', 'ÉDERSON S.'),
  ('BRA', 3, 'DF', 'GABRIEL'),
  ('BRA', 4, 'DF', 'MARQUINHOS'),
  ('BRA', 5, 'MF', 'CASEMIRO'),
  ('BRA', 6, 'DF', 'ALEX SANDRO'),
  ('BRA', 7, 'FW', 'VINI JR.'),
  ('BRA', 8, 'MF', 'BRUNO G.'),
  ('BRA', 9, 'FW', 'CUNHA'),
  ('BRA', 10, 'FW', 'NEYMAR JR'),
  ('BRA', 11, 'FW', 'RAPHINHA'),
  ('BRA', 12, 'GK', 'WEVERTON'),
  ('BRA', 13, 'DF', 'DANILO'),
  ('BRA', 14, 'DF', 'BREMER'),
  ('BRA', 15, 'DF', 'LÉO PEREIRA'),
  ('BRA', 16, 'DF', 'DOUGLAS S.'),
  ('BRA', 17, 'MF', 'FABINHO'),
  ('BRA', 18, 'MF', 'DANILO S.'),
  ('BRA', 19, 'FW', 'ENDRICK'),
  ('BRA', 20, 'MF', 'L. PAQUETÁ'),
  ('BRA', 21, 'FW', 'L. HENRIQUE'),
  ('BRA', 22, 'FW', 'MARTINELLI'),
  ('BRA', 23, 'GK', 'EDERSON'),
  ('BRA', 24, 'DF', 'IBAÑEZ'),
  ('BRA', 25, 'FW', 'THIAGO'),
  ('BRA', 26, 'FW', 'RAYAN'),
  ('CPV', 1, 'GK', 'VOZINHA'),
  ('CPV', 2, 'DF', 'STOPIRA'),
  ('CPV', 3, 'DF', 'BORGES'),
  ('CPV', 4, 'DF', 'LOPES'),
  ('CPV', 5, 'DF', 'COSTA'),
  ('CPV', 6, 'MF', 'KEVIN L.'),
  ('CPV', 7, 'MF', 'JOVANE'),
  ('CPV', 8, 'MF', 'JOÃO PAULO'),
  ('CPV', 9, 'FW', 'BENCHIMOL'),
  ('CPV', 10, 'MF', 'MONTEIRO'),
  ('CPV', 11, 'MF', 'RODRIGUES'),
  ('CPV', 12, 'GK', 'MARCIO'),
  ('CPV', 13, 'DF', 'LOPES CABRAL'),
  ('CPV', 14, 'MF', 'D. DUARTE'),
  ('CPV', 15, 'MF', 'L. DUARTE'),
  ('CPV', 16, 'MF', 'Y. SEMEDO'),
  ('CPV', 17, 'MF', 'SEMEDO'),
  ('CPV', 18, 'MF', 'ARCANJO'),
  ('CPV', 19, 'FW', 'LIVRAMENTO'),
  ('CPV', 20, 'FW', 'RYAN'),
  ('CPV', 21, 'MF', 'DA COSTA'),
  ('CPV', 22, 'DF', 'MOREIRA'),
  ('CPV', 23, 'GK', 'DOS SANTOS'),
  ('CPV', 24, 'DF', 'WAGNER P.'),
  ('CPV', 25, 'DF', 'KELVIN'),
  ('CPV', 26, 'MF', 'HÉLIO'),
  ('CAN', 1, 'GK', 'ST. CLAIR'),
  ('CAN', 2, 'DF', 'JOHNSTON'),
  ('CAN', 3, 'DF', 'JONES'),
  ('CAN', 4, 'DF', 'DE FOUGEROLLES'),
  ('CAN', 5, 'DF', 'WATERMAN'),
  ('CAN', 6, 'MF', 'CHOINIÈRE'),
  ('CAN', 7, 'MF', 'EUSTÁQUIO'),
  ('CAN', 8, 'MF', 'KONÉ'),
  ('CAN', 9, 'FW', 'LARIN'),
  ('CAN', 10, 'FW', 'J. DAVID'),
  ('CAN', 11, 'MF', 'MILLAR'),
  ('CAN', 12, 'FW', 'OLUWASEYI'),
  ('CAN', 13, 'DF', 'CORNELIUS'),
  ('CAN', 14, 'MF', 'SHAFFELBURG'),
  ('CAN', 15, 'DF', 'BOMBITO'),
  ('CAN', 16, 'GK', 'CRÉPEAU'),
  ('CAN', 17, 'FW', 'BUCHANAN'),
  ('CAN', 18, 'GK', 'GOODMAN'),
  ('CAN', 19, 'DF', 'DAVIES'),
  ('CAN', 20, 'FW', 'AHMED'),
  ('CAN', 21, 'MF', 'OSORIO'),
  ('CAN', 22, 'DF', 'LARYEA'),
  ('CAN', 23, 'DF', 'SIGUR'),
  ('CAN', 24, 'FW', 'PROMISE'),
  ('CAN', 25, 'MF', 'SALIBA'),
  ('CAN', 26, 'FW', 'NELSON'),
  ('COL', 1, 'GK', 'OSPINA'),
  ('COL', 2, 'DF', 'D. MUÑOZ'),
  ('COL', 3, 'DF', 'J. LUCUMI'),
  ('COL', 4, 'DF', 'ARIAS'),
  ('COL', 5, 'MF', 'K. CASTAÑO'),
  ('COL', 6, 'MF', 'RICHARD RIOS'),
  ('COL', 7, 'FW', 'LUIS DIAZ'),
  ('COL', 8, 'MF', 'CARRASCAL'),
  ('COL', 9, 'FW', 'CORDOBA'),
  ('COL', 10, 'MF', 'JAMES'),
  ('COL', 11, 'MF', 'J. ARIAS'),
  ('COL', 12, 'GK', 'C. VARGAS'),
  ('COL', 13, 'DF', 'Y. MINA'),
  ('COL', 14, 'DF', 'PUERTA'),
  ('COL', 15, 'MF', 'PORTILLA'),
  ('COL', 16, 'MF', 'J. LERMA'),
  ('COL', 17, 'DF', 'J. MOJICA'),
  ('COL', 18, 'DF', 'W. DITTA'),
  ('COL', 19, 'FW', 'C. HERNANDEZ'),
  ('COL', 20, 'MF', 'QUINTERO'),
  ('COL', 21, 'FW', 'CAMPAZ'),
  ('COL', 22, 'DF', 'MACHADO'),
  ('COL', 23, 'DF', 'SANCHEZ'),
  ('COL', 24, 'GK', 'MONTERO'),
  ('COL', 25, 'FW', 'SUAREZ'),
  ('COL', 26, 'FW', 'A. GOMEZ'),
  ('COD', 1, 'GK', 'MPASI'),
  ('COD', 2, 'DF', 'WAN BISSAKA'),
  ('COD', 3, 'DF', 'KAPUADI'),
  ('COD', 4, 'DF', 'TUANZEBE'),
  ('COD', 5, 'DF', 'BATUBINSIKA'),
  ('COD', 6, 'MF', 'MUKAU'),
  ('COD', 7, 'MF', 'MBUKU'),
  ('COD', 8, 'MF', 'MOUTOUSSAMY'),
  ('COD', 9, 'FW', 'CIPENGA'),
  ('COD', 10, 'MF', 'BONGONDA'),
  ('COD', 11, 'FW', 'KAKUTA'),
  ('COD', 12, 'DF', 'J. KAYEMBE'),
  ('COD', 13, 'FW', 'MESCHACK'),
  ('COD', 14, 'MF', 'SADIKI'),
  ('COD', 15, 'MF', 'TSHIBOLA'),
  ('COD', 16, 'GK', 'FAYULU'),
  ('COD', 17, 'FW', 'BAKAMBU'),
  ('COD', 18, 'MF', 'PICKEL'),
  ('COD', 19, 'FW', 'MAYELE'),
  ('COD', 20, 'FW', 'WISSA'),
  ('COD', 21, 'GK', 'EPOLO'),
  ('COD', 22, 'DF', 'MBEMBA'),
  ('COD', 23, 'FW', 'BANZA'),
  ('COD', 24, 'DF', 'KALULU'),
  ('COD', 25, 'MF', 'E. KAYEMBE'),
  ('COD', 26, 'DF', 'MASUAKU'),
  ('CRO', 1, 'GK', 'LIVAKOVIĆ'),
  ('CRO', 2, 'DF', 'STANIŠIĆ'),
  ('CRO', 3, 'DF', 'PONGRAČIĆ'),
  ('CRO', 4, 'DF', 'GVARDIOL'),
  ('CRO', 5, 'DF', 'ĆALETA-CAR'),
  ('CRO', 6, 'DF', 'ŠUTALO'),
  ('CRO', 7, 'MF', 'MORO'),
  ('CRO', 8, 'MF', 'KOVAČIĆ'),
  ('CRO', 9, 'FW', 'KRAMARIĆ'),
  ('CRO', 10, 'MF', 'MODRIĆ'),
  ('CRO', 11, 'FW', 'BUDIMIR'),
  ('CRO', 12, 'GK', 'PANDUR'),
  ('CRO', 13, 'MF', 'VLAŠIĆ'),
  ('CRO', 14, 'FW', 'PERIŠIĆ'),
  ('CRO', 15, 'MF', 'PAŠALIĆ'),
  ('CRO', 16, 'MF', 'BATURINA'),
  ('CRO', 17, 'MF', 'P. SUČIĆ'),
  ('CRO', 18, 'DF', 'JAKIĆ'),
  ('CRO', 19, 'MF', 'FRUK'),
  ('CRO', 20, 'FW', 'MATANOVIĆ'),
  ('CRO', 21, 'MF', 'SUČIĆ'),
  ('CRO', 22, 'DF', 'VUŠKOVIĆ'),
  ('CRO', 23, 'GK', 'KOTARSKI'),
  ('CRO', 24, 'FW', 'M. PAŠALIĆ'),
  ('CRO', 25, 'DF', 'ERLIĆ'),
  ('CRO', 26, 'FW', 'MUSA'),
  ('CUW', 1, 'GK', 'ROOM'),
  ('CUW', 2, 'DF', 'SAMBO'),
  ('CUW', 3, 'DF', 'GAARI'),
  ('CUW', 4, 'DF', 'VAN EIJMA'),
  ('CUW', 5, 'DF', 'FLORANUS'),
  ('CUW', 6, 'MF', 'ROEMERATOE'),
  ('CUW', 7, 'MF', 'J. BACUNA'),
  ('CUW', 8, 'MF', 'COMENENCIA'),
  ('CUW', 9, 'FW', 'LOCADIA'),
  ('CUW', 10, 'MF', 'L. BACUNA'),
  ('CUW', 11, 'FW', 'ANTONISSE'),
  ('CUW', 12, 'FW', 'HANSEN'),
  ('CUW', 13, 'FW', 'NOSLIN'),
  ('CUW', 14, 'FW', 'GORRÉ'),
  ('CUW', 15, 'MF', 'MARTHA'),
  ('CUW', 16, 'FW', 'MARGARITHA'),
  ('CUW', 17, 'FW', 'KUWAS'),
  ('CUW', 18, 'DF', 'OBISPO'),
  ('CUW', 19, 'FW', 'KASTANEER'),
  ('CUW', 20, 'DF', 'BRENET'),
  ('CUW', 21, 'MF', 'CHONG'),
  ('CUW', 22, 'MF', 'FELIDA'),
  ('CUW', 23, 'DF', 'BAZOER'),
  ('CUW', 24, 'DF', 'FONVILLE'),
  ('CUW', 25, 'GK', 'BODAK'),
  ('CUW', 26, 'GK', 'DOORNBUSCH'),
  ('CZE', 1, 'GK', 'KOVÁŘ'),
  ('CZE', 2, 'DF', 'ZIMA'),
  ('CZE', 3, 'DF', 'HOLEŠ'),
  ('CZE', 4, 'DF', 'HRANÁČ'),
  ('CZE', 5, 'DF', 'COUFAL'),
  ('CZE', 6, 'DF', 'CHALOUPEK'),
  ('CZE', 7, 'DF', 'KREJČÍ'),
  ('CZE', 8, 'MF', 'DARIDA'),
  ('CZE', 9, 'FW', 'HLOŽEK'),
  ('CZE', 10, 'FW', 'SCHICK'),
  ('CZE', 11, 'FW', 'KUCHTA'),
  ('CZE', 12, 'MF', 'ČERV'),
  ('CZE', 13, 'FW', 'CHYTIL'),
  ('CZE', 14, 'DF', 'JURÁSEK'),
  ('CZE', 15, 'FW', 'ŠULC'),
  ('CZE', 16, 'GK', 'STANĚK'),
  ('CZE', 17, 'MF', 'PROVOD'),
  ('CZE', 18, 'MF', 'SADÍLEK'),
  ('CZE', 19, 'FW', 'CHORÝ'),
  ('CZE', 20, 'DF', 'ZELENÝ'),
  ('CZE', 21, 'DF', 'DOUDĚRA'),
  ('CZE', 22, 'MF', 'SOUČEK'),
  ('CZE', 23, 'GK', 'HORNÍČEK'),
  ('CZE', 24, 'MF', 'SOJKA'),
  ('CZE', 25, 'MF', 'SOCHŮREK'),
  ('CZE', 26, 'FW', 'VIŠINSKÝ'),
  ('CIV', 1, 'GK', 'Y. FOFANA'),
  ('CIV', 2, 'DF', 'O. DIOMANDE'),
  ('CIV', 3, 'DF', 'G. KONAN'),
  ('CIV', 4, 'MF', 'SERI'),
  ('CIV', 5, 'DF', 'SINGO'),
  ('CIV', 6, 'MF', 'FOFANA'),
  ('CIV', 7, 'DF', 'KOSSOUNOU'),
  ('CIV', 8, 'MF', 'KESSIE'),
  ('CIV', 9, 'FW', 'BONNY'),
  ('CIV', 10, 'FW', 'ADINGRA'),
  ('CIV', 11, 'FW', 'YAN DIOMANDE'),
  ('CIV', 12, 'FW', 'WAHI'),
  ('CIV', 13, 'DF', 'OPERI'),
  ('CIV', 14, 'FW', 'DIAKITE'),
  ('CIV', 15, 'FW', 'AMAD'),
  ('CIV', 16, 'GK', 'KONE'),
  ('CIV', 17, 'DF', 'G. DOUE'),
  ('CIV', 18, 'MF', 'SANGARE'),
  ('CIV', 19, 'FW', 'PEPE'),
  ('CIV', 20, 'DF', 'AGBADOU'),
  ('CIV', 21, 'DF', 'NDICKA'),
  ('CIV', 22, 'FW', 'GUESSAND'),
  ('CIV', 23, 'GK', 'LAFONT'),
  ('CIV', 24, 'FW', 'TOURE'),
  ('CIV', 25, 'MF', 'GUIAGON'),
  ('CIV', 26, 'MF', 'INAO'),
  ('ECU', 1, 'GK', 'GALINDEZ'),
  ('ECU', 2, 'DF', 'TORRES'),
  ('ECU', 3, 'DF', 'HINCAPIE'),
  ('ECU', 4, 'DF', 'ORDÓÑEZ'),
  ('ECU', 5, 'MF', 'ALCIVAR'),
  ('ECU', 6, 'DF', 'PACHO'),
  ('ECU', 7, 'DF', 'ESTUPIÑÁN'),
  ('ECU', 8, 'MF', 'A. VALENCIA'),
  ('ECU', 9, 'FW', 'YEBOAH ZAMORA'),
  ('ECU', 10, 'MF', 'KENDRY'),
  ('ECU', 11, 'FW', 'RODRIGUEZ'),
  ('ECU', 12, 'GK', 'RAMÍREZ'),
  ('ECU', 13, 'FW', 'E. VALENCIA'),
  ('ECU', 14, 'MF', 'MINDA'),
  ('ECU', 15, 'MF', 'VITE'),
  ('ECU', 16, 'FW', 'J. CAICEDO'),
  ('ECU', 17, 'DF', 'PRECIADO'),
  ('ECU', 18, 'MF', 'CASTILLO'),
  ('ECU', 19, 'FW', 'PLATA'),
  ('ECU', 20, 'FW', 'ANGULO'),
  ('ECU', 21, 'MF', 'FRANCO'),
  ('ECU', 22, 'GK', 'VALLE'),
  ('ECU', 23, 'MF', 'M. CAICEDO'),
  ('ECU', 24, 'FW', 'AREVALO'),
  ('ECU', 25, 'DF', 'POROZO'),
  ('ECU', 26, 'DF', 'MEDINA'),
  ('EGY', 1, 'GK', 'M. ELSHENAWY'),
  ('EGY', 2, 'DF', 'YASSER'),
  ('EGY', 3, 'DF', 'M. HANY'),
  ('EGY', 4, 'DF', 'HOSSAM'),
  ('EGY', 5, 'DF', 'R. RABIAA'),
  ('EGY', 6, 'DF', 'M. ABDELMONIEM'),
  ('EGY', 7, 'FW', 'M. TREZEGUET'),
  ('EGY', 8, 'MF', 'E. ASHOUR'),
  ('EGY', 9, 'FW', 'ABDELKARIM'),
  ('EGY', 10, 'FW', 'M. SALAH'),
  ('EGY', 11, 'MF', 'ZICO'),
  ('EGY', 12, 'FW', 'H. HASSAN'),
  ('EGY', 13, 'DF', 'A. FATOUH'),
  ('EGY', 14, 'MF', 'H. FATHY'),
  ('EGY', 15, 'DF', 'K. HAFEZ'),
  ('EGY', 16, 'GK', 'M. SOLIMAN'),
  ('EGY', 17, 'MF', 'M. LASHIN'),
  ('EGY', 18, 'MF', 'DONGA'),
  ('EGY', 19, 'MF', 'M. ATTIA'),
  ('EGY', 20, 'FW', 'I. ADEL'),
  ('EGY', 21, 'MF', 'M. SABER'),
  ('EGY', 22, 'FW', 'MARMOUSH'),
  ('EGY', 23, 'GK', 'SHOUBIR'),
  ('EGY', 24, 'DF', 'T. ALAA'),
  ('EGY', 25, 'FW', 'ZIZO'),
  ('EGY', 26, 'GK', 'M. ALAA'),
  ('ENG', 1, 'GK', 'PICKFORD'),
  ('ENG', 2, 'DF', 'KONSA'),
  ('ENG', 3, 'DF', 'O''REILLY'),
  ('ENG', 4, 'MF', 'RICE'),
  ('ENG', 5, 'DF', 'STONES'),
  ('ENG', 6, 'DF', 'GUÉHI'),
  ('ENG', 7, 'FW', 'SAKA'),
  ('ENG', 8, 'MF', 'ANDERSON'),
  ('ENG', 9, 'FW', 'KANE'),
  ('ENG', 10, 'MF', 'BELLINGHAM'),
  ('ENG', 11, 'FW', 'RASHFORD'),
  ('ENG', 12, 'DF', 'CHALOBAH'),
  ('ENG', 13, 'GK', 'D. HENDERSON'),
  ('ENG', 14, 'MF', 'HENDERSON'),
  ('ENG', 15, 'DF', 'BURN'),
  ('ENG', 16, 'MF', 'MAINOO'),
  ('ENG', 17, 'MF', 'ROGERS'),
  ('ENG', 18, 'FW', 'GORDON'),
  ('ENG', 19, 'FW', 'WATKINS'),
  ('ENG', 20, 'FW', 'MADUEKE'),
  ('ENG', 21, 'MF', 'EZE'),
  ('ENG', 22, 'FW', 'TONEY'),
  ('ENG', 23, 'GK', 'TRAFFORD'),
  ('ENG', 24, 'DF', 'JAMES'),
  ('ENG', 25, 'DF', 'SPENCE'),
  ('ENG', 26, 'DF', 'QUANSAH'),
  ('FRA', 1, 'GK', 'SAMBA'),
  ('FRA', 2, 'DF', 'GUSTO'),
  ('FRA', 3, 'DF', 'DIGNE'),
  ('FRA', 4, 'DF', 'UPAMECANO'),
  ('FRA', 5, 'DF', 'KOUNDE'),
  ('FRA', 6, 'MF', 'KONE'),
  ('FRA', 7, 'FW', 'DEMBELE'),
  ('FRA', 8, 'MF', 'TCHOUAMENI'),
  ('FRA', 9, 'FW', 'THURAM'),
  ('FRA', 10, 'FW', 'MBAPPE'),
  ('FRA', 11, 'FW', 'OLISE'),
  ('FRA', 12, 'FW', 'BARCOLA'),
  ('FRA', 13, 'MF', 'KANTE'),
  ('FRA', 14, 'MF', 'RABIOT'),
  ('FRA', 15, 'DF', 'KONATE'),
  ('FRA', 16, 'GK', 'MAIGNAN'),
  ('FRA', 17, 'DF', 'SALIBA'),
  ('FRA', 18, 'MF', 'ZAIRE-EMERY'),
  ('FRA', 19, 'DF', 'T. HERNANDEZ'),
  ('FRA', 20, 'FW', 'DOUE'),
  ('FRA', 21, 'DF', 'L. HERNANDEZ'),
  ('FRA', 22, 'FW', 'MATETA'),
  ('FRA', 23, 'GK', 'RISSER'),
  ('FRA', 24, 'MF', 'CHERKI'),
  ('FRA', 25, 'MF', 'AKLIOUCHE'),
  ('FRA', 26, 'DF', 'LACROIX'),
  ('GER', 1, 'GK', 'NEUER'),
  ('GER', 2, 'DF', 'RÜDIGER'),
  ('GER', 3, 'DF', 'ANTON'),
  ('GER', 4, 'DF', 'TAH'),
  ('GER', 5, 'MF', 'PAVLOVIĆ'),
  ('GER', 6, 'DF', 'KIMMICH'),
  ('GER', 7, 'FW', 'HAVERTZ'),
  ('GER', 8, 'MF', 'GORETZKA'),
  ('GER', 9, 'MF', 'LEWELING'),
  ('GER', 10, 'MF', 'MUSIALA'),
  ('GER', 11, 'FW', 'WOLTEMADE'),
  ('GER', 12, 'GK', 'BAUMANN'),
  ('GER', 13, 'MF', 'GROß'),
  ('GER', 14, 'FW', 'BEIER'),
  ('GER', 15, 'DF', 'SCHLOTTERBECK'),
  ('GER', 16, 'MF', 'STILLER'),
  ('GER', 17, 'MF', 'WIRTZ'),
  ('GER', 18, 'DF', 'BROWN'),
  ('GER', 19, 'MF', 'SANÉ'),
  ('GER', 20, 'MF', 'AMIRI'),
  ('GER', 21, 'GK', 'NÜBEL'),
  ('GER', 22, 'DF', 'RAUM'),
  ('GER', 23, 'MF', 'NMECHA'),
  ('GER', 24, 'DF', 'THIAW'),
  ('GER', 25, 'MF', 'OUÉDRAOGO'),
  ('GER', 26, 'FW', 'UNDAV'),
  ('GHA', 1, 'GK', 'ZIGI'),
  ('GHA', 2, 'DF', 'ALIDU SEIDU'),
  ('GHA', 3, 'MF', 'YIRENKYI'),
  ('GHA', 4, 'DF', 'ADJETEY'),
  ('GHA', 5, 'MF', 'PARTEY'),
  ('GHA', 6, 'DF', 'A. MUMIN'),
  ('GHA', 7, 'FW', 'A. FATAWU'),
  ('GHA', 8, 'MF', 'SIBO'),
  ('GHA', 9, 'FW', 'J. AYEW'),
  ('GHA', 10, 'FW', 'ASANTE'),
  ('GHA', 11, 'MF', 'SEMENYO'),
  ('GHA', 12, 'GK', 'ANANG'),
  ('GHA', 13, 'FW', 'BONSU BAAH'),
  ('GHA', 14, 'DF', 'MENSAH'),
  ('GHA', 15, 'MF', 'OWUSU'),
  ('GHA', 16, 'GK', 'B. ASARE'),
  ('GHA', 17, 'DF', 'BABA'),
  ('GHA', 18, 'DF', 'OPOKU'),
  ('GHA', 19, 'FW', 'WILLIAMS'),
  ('GHA', 20, 'MF', 'BOAKYE'),
  ('GHA', 21, 'DF', 'OPPONG'),
  ('GHA', 22, 'FW', 'KAMALDEEN'),
  ('GHA', 23, 'DF', 'LUCKASSEN'),
  ('GHA', 24, 'FW', 'NUAMAH'),
  ('GHA', 25, 'FW', 'PRINCE'),
  ('GHA', 26, 'DF', 'SENEYA'),
  ('HAI', 1, 'GK', 'PLACIDE'),
  ('HAI', 2, 'DF', 'ARCUS'),
  ('HAI', 3, 'DF', 'THERMONCY'),
  ('HAI', 4, 'DF', 'ADE'),
  ('HAI', 5, 'DF', 'DELCROIX'),
  ('HAI', 6, 'MF', 'SAINTE'),
  ('HAI', 7, 'FW', 'ETIENNE JR'),
  ('HAI', 8, 'DF', 'EXPERIENCE'),
  ('HAI', 9, 'FW', 'NAZON'),
  ('HAI', 10, 'MF', 'BELLEGARDE'),
  ('HAI', 11, 'FW', 'LOUICIUS'),
  ('HAI', 12, 'GK', 'A. PIERRE'),
  ('HAI', 13, 'DF', 'LACROIX'),
  ('HAI', 14, 'DF', 'METUSALA'),
  ('HAI', 15, 'FW', 'PROVIDENCE'),
  ('HAI', 16, 'FW', 'JOSEPH'),
  ('HAI', 17, 'MF', 'JEAN-JACQUES'),
  ('HAI', 18, 'FW', 'ISIDOR'),
  ('HAI', 19, 'FW', 'FORTUNE'),
  ('HAI', 20, 'FW', 'PIERROT'),
  ('HAI', 21, 'FW', 'CASIMIR'),
  ('HAI', 22, 'DF', 'DUVERNE'),
  ('HAI', 23, 'GK', 'DUVERGER'),
  ('HAI', 24, 'DF', 'PAUGAIN'),
  ('HAI', 25, 'MF', 'SIMON'),
  ('HAI', 26, 'MF', 'W. PIERRE'),
  ('IRN', 1, 'GK', 'BEIRANVAND'),
  ('IRN', 2, 'DF', 'SALEH'),
  ('IRN', 3, 'DF', 'E. HAJISAFI'),
  ('IRN', 4, 'DF', 'SHOJA'),
  ('IRN', 5, 'DF', 'M. MOHAMMADI'),
  ('IRN', 6, 'MF', 'S. EZATOLAHI'),
  ('IRN', 7, 'MF', 'A. JAHANBAKHSH'),
  ('IRN', 8, 'MF', 'M. MOHEBBI'),
  ('IRN', 9, 'FW', 'TAREMI'),
  ('IRN', 10, 'FW', 'MEHDI GHAYEDI'),
  ('IRN', 11, 'FW', 'A. ALIPOUR'),
  ('IRN', 12, 'GK', 'PAYAM'),
  ('IRN', 13, 'DF', 'KANANI'),
  ('IRN', 14, 'MF', 'GHODDOS'),
  ('IRN', 15, 'MF', 'ROOZBEH'),
  ('IRN', 16, 'MF', 'M. TORABI'),
  ('IRN', 17, 'DF', 'ARYA'),
  ('IRN', 18, 'FW', 'AMIRHOSSEIN'),
  ('IRN', 19, 'DF', 'ALI'),
  ('IRN', 20, 'FW', 'SHAHRIYAR'),
  ('IRN', 21, 'MF', 'MOHAMMAD'),
  ('IRN', 22, 'GK', 'HOSSEINI'),
  ('IRN', 23, 'DF', 'RAMIN'),
  ('IRN', 24, 'FW', 'DARGAHI'),
  ('IRN', 25, 'DF', 'DANIAL'),
  ('IRN', 26, 'MF', 'RAZAGH'),
  ('IRQ', 1, 'GK', 'FAHAD'),
  ('IRQ', 2, 'DF', 'REBIN'),
  ('IRQ', 3, 'DF', 'HUSSEIN'),
  ('IRQ', 4, 'DF', 'ZAID T.'),
  ('IRQ', 5, 'DF', 'AKAM'),
  ('IRQ', 6, 'DF', 'MUNAF'),
  ('IRQ', 7, 'MF', 'YOUSSEF'),
  ('IRQ', 8, 'MF', 'IBRAHIM'),
  ('IRQ', 9, 'FW', 'AL-HAMADI'),
  ('IRQ', 10, 'FW', 'MOHANAD'),
  ('IRQ', 11, 'FW', 'AHMED Q.'),
  ('IRQ', 12, 'GK', 'JALAL'),
  ('IRQ', 13, 'FW', 'ALI Y.'),
  ('IRQ', 14, 'MF', 'Z. IQBAL'),
  ('IRQ', 15, 'DF', 'AHMED H.'),
  ('IRQ', 16, 'MF', 'AL-AMMARI'),
  ('IRQ', 17, 'FW', 'ALI J.'),
  ('IRQ', 18, 'FW', 'AYMEN'),
  ('IRQ', 19, 'MF', 'K. YAKOB'),
  ('IRQ', 20, 'MF', 'AIMAR'),
  ('IRQ', 21, 'FW', 'MARKO'),
  ('IRQ', 22, 'GK', 'AHMED B.'),
  ('IRQ', 23, 'DF', 'DOSKI'),
  ('IRQ', 24, 'MF', 'ZAID I.'),
  ('IRQ', 25, 'DF', 'MUSTAFA'),
  ('IRQ', 26, 'DF', 'FRANS'),
  ('JPN', 1, 'GK', 'SUZUKI'),
  ('JPN', 2, 'DF', 'SUGAWARA'),
  ('JPN', 3, 'DF', 'TANIGUCHI'),
  ('JPN', 4, 'DF', 'ITAKURA'),
  ('JPN', 5, 'DF', 'NAGATOMO'),
  ('JPN', 6, 'FW', 'MACHINO'),
  ('JPN', 7, 'MF', 'TANAKA'),
  ('JPN', 8, 'MF', 'KUBO'),
  ('JPN', 9, 'FW', 'GOTO'),
  ('JPN', 10, 'MF', 'DOAN'),
  ('JPN', 11, 'MF', 'DAIZEN'),
  ('JPN', 12, 'GK', 'OSAKO'),
  ('JPN', 13, 'MF', 'NAKAMURA'),
  ('JPN', 14, 'MF', 'ITO'),
  ('JPN', 15, 'MF', 'KAMADA'),
  ('JPN', 16, 'DF', 'WATANABE'),
  ('JPN', 17, 'MF', 'Y. SUZUKI'),
  ('JPN', 18, 'FW', 'AYASE'),
  ('JPN', 19, 'FW', 'OGAWA'),
  ('JPN', 20, 'DF', 'SEKO'),
  ('JPN', 21, 'DF', 'H. ITO'),
  ('JPN', 22, 'DF', 'TOMIYASU'),
  ('JPN', 23, 'GK', 'HAYAKAWA'),
  ('JPN', 24, 'MF', 'SANO'),
  ('JPN', 25, 'DF', 'J. SUZUKI'),
  ('JPN', 26, 'FW', 'SHIOGAI'),
  ('JOR', 1, 'GK', 'YAZEED'),
  ('JOR', 2, 'DF', 'ABU HASHEESH'),
  ('JOR', 3, 'DF', 'NASIB'),
  ('JOR', 4, 'DF', 'ABU DAHAB'),
  ('JOR', 5, 'DF', 'ALARAB'),
  ('JOR', 6, 'MF', 'JAMOUS'),
  ('JOR', 7, 'FW', 'ABU ZRAIQ'),
  ('JOR', 8, 'MF', 'ALRAWABDEH'),
  ('JOR', 9, 'FW', 'OLWAN'),
  ('JOR', 10, 'FW', 'ALTAMARI'),
  ('JOR', 11, 'FW', 'ODEH'),
  ('JOR', 12, 'GK', 'BANI ATEYAH'),
  ('JOR', 13, 'FW', 'ALMARDI'),
  ('JOR', 14, 'MF', 'RAJA''EI'),
  ('JOR', 15, 'MF', 'SA''DEH'),
  ('JOR', 16, 'DF', 'ABU ALNADI'),
  ('JOR', 17, 'DF', 'SALEEM'),
  ('JOR', 18, 'MF', 'ABU GHOUSH'),
  ('JOR', 19, 'DF', 'SA''ED'),
  ('JOR', 20, 'MF', 'ABU TAHA'),
  ('JOR', 21, 'MF', 'NIZAR'),
  ('JOR', 22, 'GK', 'ALFAKHORI'),
  ('JOR', 23, 'DF', 'EHSAN'),
  ('JOR', 24, 'FW', 'AZAIZEH'),
  ('JOR', 25, 'MF', 'ALDAOUD'),
  ('JOR', 26, 'DF', 'BADAWI'),
  ('KOR', 1, 'GK', 'SEUNGGYU'),
  ('KOR', 2, 'DF', 'HANBEOM'),
  ('KOR', 3, 'MF', 'GIHYUK'),
  ('KOR', 4, 'DF', 'MINJAE'),
  ('KOR', 5, 'DF', 'TAEHYEON'),
  ('KOR', 6, 'MF', 'INBEOM'),
  ('KOR', 7, 'FW', 'HEUNGMIN'),
  ('KOR', 8, 'MF', 'SEUNGHO'),
  ('KOR', 9, 'FW', 'GUESUNG'),
  ('KOR', 10, 'MF', 'JAESUNG'),
  ('KOR', 11, 'MF', 'HEECHAN'),
  ('KOR', 12, 'GK', 'BUMKEUN'),
  ('KOR', 13, 'DF', 'TAESEOK'),
  ('KOR', 14, 'DF', 'WIJE'),
  ('KOR', 15, 'DF', 'MOONHWAN'),
  ('KOR', 16, 'DF', 'JINSEOB'),
  ('KOR', 17, 'MF', 'JUNHO'),
  ('KOR', 18, 'FW', 'HYEONGYU'),
  ('KOR', 19, 'MF', 'KANGIN'),
  ('KOR', 20, 'MF', 'HYUNJUN'),
  ('KOR', 21, 'GK', 'HYEONWOO'),
  ('KOR', 22, 'DF', 'YOUNGWOO'),
  ('KOR', 23, 'DF', 'JENS'),
  ('KOR', 24, 'MF', 'JINGYU'),
  ('KOR', 25, 'MF', 'JISUNG'),
  ('KOR', 26, 'MF', 'DONGGYEONG'),
  ('MEX', 1, 'GK', 'R. RANGEL'),
  ('MEX', 2, 'DF', 'J. SÁNCHEZ'),
  ('MEX', 3, 'DF', 'C. MONTES'),
  ('MEX', 4, 'DF', 'E. ÁLVAREZ'),
  ('MEX', 5, 'DF', 'J. VÁSQUEZ'),
  ('MEX', 6, 'MF', 'E. LIRA'),
  ('MEX', 7, 'MF', 'L. ROMO'),
  ('MEX', 8, 'MF', 'FIDALGO'),
  ('MEX', 9, 'FW', 'RAÚL'),
  ('MEX', 10, 'FW', 'A. VEGA'),
  ('MEX', 11, 'FW', 'S. GIMENEZ'),
  ('MEX', 12, 'GK', 'C. ACEVEDO'),
  ('MEX', 13, 'GK', 'G. OCHOA'),
  ('MEX', 14, 'FW', 'A. GONZÁLEZ'),
  ('MEX', 15, 'DF', 'I. REYES'),
  ('MEX', 16, 'FW', 'J. QUIÑONES'),
  ('MEX', 17, 'MF', 'ORBELÍN'),
  ('MEX', 18, 'MF', 'O. VARGAS'),
  ('MEX', 19, 'MF', 'G. MORA'),
  ('MEX', 20, 'DF', 'M. CHÁVEZ'),
  ('MEX', 21, 'FW', 'C. HUERTA'),
  ('MEX', 22, 'FW', 'G. MARTÍNEZ'),
  ('MEX', 23, 'DF', 'J. GALLARDO'),
  ('MEX', 24, 'MF', 'L. CHÁVEZ'),
  ('MEX', 25, 'FW', 'R. ALVARADO'),
  ('MEX', 26, 'MF', 'B. GUTIÉRREZ'),
  ('MAR', 1, 'GK', 'BONO'),
  ('MAR', 2, 'DF', 'HAKIMI'),
  ('MAR', 3, 'DF', 'MAZRAOUI'),
  ('MAR', 4, 'MF', 'AMRABAT'),
  ('MAR', 5, 'DF', 'SAADANE'),
  ('MAR', 6, 'MF', 'BOUADDI'),
  ('MAR', 7, 'MF', 'TALBI'),
  ('MAR', 8, 'MF', 'OUNAHI'),
  ('MAR', 9, 'FW', 'RAHIMI'),
  ('MAR', 10, 'FW', 'BRAHIM'),
  ('MAR', 11, 'MF', 'SAIBARI'),
  ('MAR', 12, 'GK', 'EL KAJOUI'),
  ('MAR', 13, 'DF', 'EL OUAHDI'),
  ('MAR', 14, 'DF', 'ISSA'),
  ('MAR', 15, 'MF', 'EL MOURABET'),
  ('MAR', 16, 'MF', 'YASSINE'),
  ('MAR', 17, 'FW', 'SBAÏ'),
  ('MAR', 18, 'DF', 'RIAD'),
  ('MAR', 19, 'DF', 'BELAMMARI'),
  ('MAR', 20, 'FW', 'EL KAABI'),
  ('MAR', 21, 'FW', 'AMAIMOUNI'),
  ('MAR', 22, 'GK', 'TAGNAOUTI'),
  ('MAR', 23, 'MF', 'EL KHANNOUSS'),
  ('MAR', 24, 'MF', 'EL AYNAOUI'),
  ('MAR', 25, 'DF', 'HALHAL'),
  ('MAR', 26, 'DF', 'SALAH-EDDINE'),
  ('NED', 1, 'GK', 'VERBRUGGEN'),
  ('NED', 2, 'DF', 'GEERTRUIDA'),
  ('NED', 3, 'MF', 'DE ROON'),
  ('NED', 4, 'DF', 'VIRGIL'),
  ('NED', 5, 'DF', 'AKÉ'),
  ('NED', 6, 'DF', 'VAN HECKE'),
  ('NED', 7, 'MF', 'KLUIVERT'),
  ('NED', 8, 'MF', 'GRAVENBERCH'),
  ('NED', 9, 'FW', 'WEGHORST'),
  ('NED', 10, 'FW', 'MEMPHIS'),
  ('NED', 11, 'FW', 'GAKPO'),
  ('NED', 12, 'DF', 'WIEFFER'),
  ('NED', 13, 'GK', 'ROEFS'),
  ('NED', 14, 'MF', 'REIJNDERS'),
  ('NED', 15, 'DF', 'VAN DE VEN'),
  ('NED', 16, 'MF', 'TIL'),
  ('NED', 17, 'FW', 'LANG'),
  ('NED', 18, 'FW', 'MALEN'),
  ('NED', 19, 'FW', 'BROBBEY'),
  ('NED', 20, 'MF', 'KOOPMEINERS'),
  ('NED', 21, 'MF', 'F. DE JONG'),
  ('NED', 22, 'DF', 'DUMFRIES'),
  ('NED', 23, 'GK', 'FLEKKEN'),
  ('NED', 24, 'FW', 'SUMMERVILLE'),
  ('NED', 25, 'DF', 'HATO'),
  ('NED', 26, 'MF', 'Q. TIMBER'),
  ('NZL', 1, 'GK', 'CROCOMBE'),
  ('NZL', 2, 'DF', 'PAYNE'),
  ('NZL', 3, 'DF', 'DE VRIES'),
  ('NZL', 4, 'DF', 'BINDON'),
  ('NZL', 5, 'DF', 'BOXALL'),
  ('NZL', 6, 'MF', 'BELL'),
  ('NZL', 7, 'FW', 'ROGERSON'),
  ('NZL', 8, 'MF', 'STAMENIC'),
  ('NZL', 9, 'FW', 'WOOD'),
  ('NZL', 10, 'MF', 'SINGH'),
  ('NZL', 11, 'MF', 'JUST'),
  ('NZL', 12, 'GK', 'PAULSEN'),
  ('NZL', 13, 'DF', 'CACACE'),
  ('NZL', 14, 'MF', 'RUFER'),
  ('NZL', 15, 'DF', 'PIJNAKER'),
  ('NZL', 16, 'DF', 'SURMAN'),
  ('NZL', 17, 'FW', 'BARBAROUSES'),
  ('NZL', 18, 'FW', 'WAINE'),
  ('NZL', 19, 'MF', 'OLD'),
  ('NZL', 20, 'MF', 'MCCOWATT'),
  ('NZL', 21, 'FW', 'RANDALL'),
  ('NZL', 22, 'GK', 'WOUD'),
  ('NZL', 23, 'MF', 'THOMAS'),
  ('NZL', 24, 'DF', 'ELLIOT'),
  ('NZL', 25, 'MF', 'BAYLISS'),
  ('NZL', 26, 'DF', 'SMITH'),
  ('NOR', 1, 'GK', 'NYLAND'),
  ('NOR', 2, 'MF', 'THORSBY'),
  ('NOR', 3, 'DF', 'VASSBAKK AJER'),
  ('NOR', 4, 'DF', 'ØSTIGÅRD'),
  ('NOR', 5, 'DF', 'MØLLER WOLFE'),
  ('NOR', 6, 'MF', 'BERG'),
  ('NOR', 7, 'FW', 'SØRLOTH'),
  ('NOR', 8, 'MF', 'BERGE'),
  ('NOR', 9, 'FW', 'BRAUT HAALAND'),
  ('NOR', 10, 'MF', 'ØDEGAARD'),
  ('NOR', 11, 'FW', 'STRAND LARSEN'),
  ('NOR', 12, 'GK', 'TANGVIK'),
  ('NOR', 13, 'GK', 'SELVIK'),
  ('NOR', 14, 'MF', 'AURSNES'),
  ('NOR', 15, 'DF', 'BJØRKAN'),
  ('NOR', 16, 'DF', 'HOLMGREN'),
  ('NOR', 17, 'DF', 'HEGGEM'),
  ('NOR', 18, 'MF', 'THORSTVEDT'),
  ('NOR', 19, 'MF', 'AASGAARD'),
  ('NOR', 20, 'FW', 'NUSA'),
  ('NOR', 21, 'MF', 'SCHJELDERUP'),
  ('NOR', 22, 'MF', 'BOBB'),
  ('NOR', 23, 'MF', 'HAUGE'),
  ('NOR', 24, 'DF', 'LANGÅS'),
  ('NOR', 25, 'DF', 'FALCHENER'),
  ('NOR', 26, 'FW', 'RYERSON'),
  ('PAN', 1, 'GK', 'MEJIA'),
  ('PAN', 2, 'DF', 'BLACKMAN'),
  ('PAN', 3, 'DF', 'CORDOBA'),
  ('PAN', 4, 'DF', 'F. ESCOBAR'),
  ('PAN', 5, 'DF', 'FARIÑA'),
  ('PAN', 6, 'MF', 'MARTÍNEZ'),
  ('PAN', 7, 'MF', 'J.L. RODRÍGUEZ'),
  ('PAN', 8, 'MF', 'CARRASQUILLA'),
  ('PAN', 9, 'FW', 'T. RODRÍGUEZ'),
  ('PAN', 10, 'MF', 'ISMAEL'),
  ('PAN', 11, 'MF', 'BÁRCENAS'),
  ('PAN', 12, 'GK', 'SAMUDIO'),
  ('PAN', 13, 'DF', 'RAMOS'),
  ('PAN', 14, 'DF', 'HARVEY'),
  ('PAN', 15, 'DF', 'DAVIS'),
  ('PAN', 16, 'DF', 'ANDRADE'),
  ('PAN', 17, 'FW', 'FAJARDO'),
  ('PAN', 18, 'FW', 'WATERMAN'),
  ('PAN', 19, 'MF', 'QUINTERO'),
  ('PAN', 20, 'MF', 'GODOY'),
  ('PAN', 21, 'MF', 'YANIS'),
  ('PAN', 22, 'GK', 'MOSQUERA'),
  ('PAN', 23, 'DF', 'A. MURILLO'),
  ('PAN', 24, 'FW', 'LONDOÑO'),
  ('PAN', 25, 'DF', 'MILLER'),
  ('PAN', 26, 'DF', 'GUTIÉRREZ'),
  ('PAR', 1, 'GK', 'FERNÁNDEZ'),
  ('PAR', 2, 'DF', 'VELÁZQUEZ'),
  ('PAR', 3, 'DF', 'ALDERETE'),
  ('PAR', 4, 'DF', 'CÁCERES'),
  ('PAR', 5, 'DF', 'BALBUENA'),
  ('PAR', 6, 'DF', 'ALONSO'),
  ('PAR', 7, 'MF', 'SOSA'),
  ('PAR', 8, 'MF', 'D. GÓMEZ'),
  ('PAR', 9, 'FW', 'SANABRIA'),
  ('PAR', 10, 'MF', 'ALMIRÓN'),
  ('PAR', 11, 'MF', 'MAURICIO'),
  ('PAR', 12, 'GK', 'O. GILL'),
  ('PAR', 13, 'DF', 'CANALE'),
  ('PAR', 14, 'MF', 'CUBAS'),
  ('PAR', 15, 'DF', 'G. GÓMEZ'),
  ('PAR', 16, 'MF', 'BOBADILLA'),
  ('PAR', 17, 'FW', 'R. GAMARRA'),
  ('PAR', 18, 'FW', 'ARCE'),
  ('PAR', 19, 'FW', 'ENCISO'),
  ('PAR', 20, 'MF', 'OJEDA'),
  ('PAR', 21, 'FW', 'AVALOS'),
  ('PAR', 22, 'GK', 'OLVEIRA'),
  ('PAR', 23, 'MF', 'GALARZA'),
  ('PAR', 24, 'MF', 'CABALLERO'),
  ('PAR', 25, 'FW', 'PITTA'),
  ('PAR', 26, 'DF', 'MAIDANA'),
  ('POR', 1, 'GK', 'DIOGO COSTA'),
  ('POR', 2, 'DF', 'N. SEMEDO'),
  ('POR', 3, 'DF', 'RÚBEN DIAS'),
  ('POR', 4, 'DF', 'TOMÁS A.'),
  ('POR', 5, 'DF', 'DALOT'),
  ('POR', 6, 'MF', 'MATHEUS N.'),
  ('POR', 7, 'FW', 'RONALDO'),
  ('POR', 8, 'MF', 'B. FERNANDES'),
  ('POR', 9, 'FW', 'G. RAMOS'),
  ('POR', 10, 'MF', 'BERNARDO'),
  ('POR', 11, 'FW', 'JOÃO FÉLIX'),
  ('POR', 12, 'GK', 'JOSÉ SÁ'),
  ('POR', 13, 'DF', 'RENATO VEIGA'),
  ('POR', 14, 'DF', 'G. INÁCIO'),
  ('POR', 15, 'MF', 'JOÃO NEVES'),
  ('POR', 16, 'FW', 'TRINCÃO'),
  ('POR', 17, 'FW', 'RAFA LEÃO'),
  ('POR', 18, 'FW', 'NETO'),
  ('POR', 19, 'FW', 'G. GUEDES'),
  ('POR', 20, 'DF', 'JOÃO CANCELO'),
  ('POR', 21, 'MF', 'R. NEVES'),
  ('POR', 22, 'GK', 'RUI SILVA'),
  ('POR', 23, 'MF', 'VITINHA'),
  ('POR', 24, 'DF', 'SAMU'),
  ('POR', 25, 'DF', 'N. MENDES'),
  ('POR', 26, 'FW', 'F. CONCEIÇÃO'),
  ('QAT', 1, 'GK', 'ABUNADA'),
  ('QAT', 2, 'DF', 'PEDRO'),
  ('QAT', 3, 'DF', 'L.MENDES'),
  ('QAT', 4, 'DF', 'GUEYE'),
  ('QAT', 5, 'DF', 'JASSEM'),
  ('QAT', 6, 'MF', 'A. AZIZ'),
  ('QAT', 7, 'FW', 'ALAAELDIN'),
  ('QAT', 8, 'FW', 'EDMILSON JR.'),
  ('QAT', 9, 'FW', 'MUNTARI'),
  ('QAT', 10, 'FW', 'ALHAYDOS'),
  ('QAT', 11, 'FW', 'AFIF'),
  ('QAT', 12, 'MF', 'KARIM'),
  ('QAT', 13, 'DF', 'AYOUB'),
  ('QAT', 14, 'DF', 'HOMAM'),
  ('QAT', 15, 'FW', 'YUSUF'),
  ('QAT', 16, 'DF', 'KHOUKHI'),
  ('QAT', 17, 'MF', 'A. ALGANEHI'),
  ('QAT', 18, 'DF', 'SULTAN'),
  ('QAT', 19, 'FW', 'ALMOEZ'),
  ('QAT', 20, 'MF', 'A. FATHY'),
  ('QAT', 21, 'GK', 'SALAH'),
  ('QAT', 22, 'GK', 'BARSHAM'),
  ('QAT', 23, 'MF', 'MADIBO'),
  ('QAT', 24, 'FW', 'TAHSIN'),
  ('QAT', 25, 'DF', 'ALHASHMI'),
  ('QAT', 26, 'FW', 'MANAI'),
  ('KSA', 1, 'GK', 'ALAQIDI'),
  ('KSA', 2, 'DF', 'MAJRASHI'),
  ('KSA', 3, 'DF', 'LAJAMI'),
  ('KSA', 4, 'DF', 'ALAMRI'),
  ('KSA', 5, 'DF', 'ALTAMBAKTI'),
  ('KSA', 6, 'MF', 'NASSER'),
  ('KSA', 7, 'MF', 'MUSAB'),
  ('KSA', 8, 'FW', 'AIMAN'),
  ('KSA', 9, 'FW', 'FERAS'),
  ('KSA', 10, 'FW', 'SALEM'),
  ('KSA', 11, 'FW', 'ALSHEHRI'),
  ('KSA', 12, 'DF', 'SAUD'),
  ('KSA', 13, 'DF', 'NAWAF'),
  ('KSA', 14, 'DF', 'KADISH'),
  ('KSA', 15, 'MF', 'ALKHAIBARI'),
  ('KSA', 16, 'MF', 'ZIYAD'),
  ('KSA', 17, 'FW', 'KHALID'),
  ('KSA', 18, 'MF', 'ALHAJJI'),
  ('KSA', 19, 'FW', 'ALHAMDDAN'),
  ('KSA', 20, 'FW', 'MANDASH'),
  ('KSA', 21, 'GK', 'ALOWAIS'),
  ('KSA', 22, 'GK', 'ALKASSAR'),
  ('KSA', 23, 'MF', 'KANNO'),
  ('KSA', 24, 'DF', 'MOTEB'),
  ('KSA', 25, 'DF', 'JEHAD'),
  ('KSA', 26, 'DF', 'MOHAMMED'),
  ('SCO', 1, 'GK', 'GUNN'),
  ('SCO', 2, 'DF', 'HICKEY'),
  ('SCO', 3, 'DF', 'ROBERTSON'),
  ('SCO', 4, 'MF', 'MCTOMINAY'),
  ('SCO', 5, 'DF', 'HANLEY'),
  ('SCO', 6, 'DF', 'TIERNEY'),
  ('SCO', 7, 'MF', 'MCGINN'),
  ('SCO', 8, 'MF', 'FLETCHER'),
  ('SCO', 9, 'FW', 'DYKES'),
  ('SCO', 10, 'FW', 'ADAMS'),
  ('SCO', 11, 'MF', 'CHRISTIE'),
  ('SCO', 12, 'GK', 'KELLY'),
  ('SCO', 13, 'DF', 'HENDRY'),
  ('SCO', 14, 'FW', 'STEWART'),
  ('SCO', 15, 'DF', 'SOUTTAR'),
  ('SCO', 16, 'DF', 'HYAM'),
  ('SCO', 17, 'FW', 'GANNON DOAK'),
  ('SCO', 18, 'FW', 'HIRST'),
  ('SCO', 19, 'MF', 'FERGUSON'),
  ('SCO', 20, 'FW', 'SHANKLAND'),
  ('SCO', 21, 'GK', 'GORDON'),
  ('SCO', 22, 'DF', 'PATTERSON'),
  ('SCO', 23, 'MF', 'MCLEAN'),
  ('SCO', 24, 'DF', 'RALSTON'),
  ('SCO', 25, 'FW', 'CURTIS'),
  ('SCO', 26, 'DF', 'MCKENNA'),
  ('SEN', 1, 'GK', 'Y. DIOUF'),
  ('SEN', 2, 'DF', 'SARR'),
  ('SEN', 3, 'DF', 'KOULIBALY'),
  ('SEN', 4, 'DF', 'SECK'),
  ('SEN', 5, 'MF', 'GANA'),
  ('SEN', 6, 'MF', 'P.I. CISS'),
  ('SEN', 7, 'FW', 'A. DIAO'),
  ('SEN', 8, 'MF', 'LAMINE'),
  ('SEN', 9, 'FW', 'BAMBA'),
  ('SEN', 10, 'FW', 'MANÉ'),
  ('SEN', 11, 'FW', 'N. JACKSON'),
  ('SEN', 12, 'FW', 'CHÉRIF'),
  ('SEN', 13, 'FW', 'NDIAYE'),
  ('SEN', 14, 'DF', 'JAKOBS'),
  ('SEN', 15, 'DF', 'DIATTA'),
  ('SEN', 16, 'GK', 'MENDY'),
  ('SEN', 17, 'MF', 'P.M. SARR'),
  ('SEN', 18, 'FW', 'ISMAÏLA'),
  ('SEN', 19, 'DF', 'NIAKHATÉ'),
  ('SEN', 20, 'FW', 'I. MBAYE'),
  ('SEN', 21, 'MF', 'H. DIARRA'),
  ('SEN', 22, 'MF', 'BARA'),
  ('SEN', 23, 'GK', 'DIAW'),
  ('SEN', 24, 'DF', 'A. MENDY'),
  ('SEN', 25, 'DF', 'DIOUF'),
  ('SEN', 26, 'MF', 'GUEYE'),
  ('RSA', 1, 'GK', 'WILLIAMS'),
  ('RSA', 2, 'DF', 'MATULUDI'),
  ('RSA', 3, 'DF', 'NDAMANE'),
  ('RSA', 4, 'MF', 'MOKOENA'),
  ('RSA', 5, 'MF', 'MBATHA'),
  ('RSA', 6, 'DF', 'MODIBA'),
  ('RSA', 7, 'FW', 'APPOLLIS'),
  ('RSA', 8, 'FW', 'MOREMI'),
  ('RSA', 9, 'FW', 'FOSTER'),
  ('RSA', 10, 'FW', 'MOFOKENG'),
  ('RSA', 11, 'MF', 'ZWANE'),
  ('RSA', 12, 'FW', 'MASEKO'),
  ('RSA', 13, 'MF', 'SITHOLE'),
  ('RSA', 14, 'DF', 'MBOKAZI'),
  ('RSA', 15, 'FW', 'RAYNERS'),
  ('RSA', 16, 'GK', 'CHAINE'),
  ('RSA', 17, 'FW', 'MAKGPA'),
  ('RSA', 18, 'DF', 'KABINI'),
  ('RSA', 19, 'DF', 'SIBISI'),
  ('RSA', 20, 'DF', 'MUDAU'),
  ('RSA', 21, 'DF', 'OKON'),
  ('RSA', 22, 'GK', 'GOSS'),
  ('RSA', 23, 'MF', 'ADAMS'),
  ('RSA', 24, 'DF', 'MAKHANYA'),
  ('RSA', 25, 'FW', 'SEBELEBELE'),
  ('RSA', 26, 'DF', 'CROSS'),
  ('ESP', 1, 'GK', 'RAYA'),
  ('ESP', 2, 'DF', 'MARC PUBILL'),
  ('ESP', 3, 'DF', 'GRIMALDO'),
  ('ESP', 4, 'DF', 'ERIC'),
  ('ESP', 5, 'DF', 'M. LLORENTE'),
  ('ESP', 6, 'MF', 'MERINO'),
  ('ESP', 7, 'FW', 'FERRAN'),
  ('ESP', 8, 'MF', 'FABIÁN'),
  ('ESP', 9, 'MF', 'GAVI'),
  ('ESP', 10, 'FW', 'OLMO'),
  ('ESP', 11, 'FW', 'YEREMY'),
  ('ESP', 12, 'DF', 'PEDRO PORRO'),
  ('ESP', 13, 'GK', 'JOAN GARCIA'),
  ('ESP', 14, 'DF', 'LAPORTE'),
  ('ESP', 15, 'MF', 'ALEX B.'),
  ('ESP', 16, 'MF', 'RODRIGO'),
  ('ESP', 17, 'FW', 'WILLIAMS JR.'),
  ('ESP', 18, 'MF', 'ZUBIMENDI'),
  ('ESP', 19, 'FW', 'LAMINE YAMAL'),
  ('ESP', 20, 'MF', 'PEDRI'),
  ('ESP', 21, 'FW', 'OYARZABAL'),
  ('ESP', 22, 'DF', 'CUBARSÍ'),
  ('ESP', 23, 'GK', 'UNAI SIMÓN'),
  ('ESP', 24, 'DF', 'CUCURELLA'),
  ('ESP', 25, 'FW', 'VICTOR M.V.'),
  ('ESP', 26, 'FW', 'B. IGLESIAS'),
  ('SWE', 1, 'GK', 'ZETTERSTRÖM'),
  ('SWE', 2, 'DF', 'LAGERBIELKE'),
  ('SWE', 3, 'DF', 'LINDELÖF'),
  ('SWE', 4, 'DF', 'HIEN'),
  ('SWE', 5, 'DF', 'GUDMUNDSSON'),
  ('SWE', 6, 'DF', 'H. JOHANSSON'),
  ('SWE', 7, 'MF', 'BERGVALL'),
  ('SWE', 8, 'DF', 'SVENSSON'),
  ('SWE', 9, 'FW', 'ISAK'),
  ('SWE', 10, 'MF', 'NYGREN'),
  ('SWE', 11, 'FW', 'ELANGA'),
  ('SWE', 12, 'GK', 'V. JOHANSSON'),
  ('SWE', 13, 'MF', 'SEMA'),
  ('SWE', 14, 'DF', 'EKDAL'),
  ('SWE', 15, 'DF', 'STARFELT'),
  ('SWE', 16, 'MF', 'KARLSTRÖM'),
  ('SWE', 17, 'FW', 'GYÖKERES'),
  ('SWE', 18, 'MF', 'AYARI'),
  ('SWE', 19, 'MF', 'SVANBERG'),
  ('SWE', 20, 'DF', 'SMITH'),
  ('SWE', 21, 'DF', 'BERNHARDSSON'),
  ('SWE', 22, 'MF', 'ZENELI'),
  ('SWE', 23, 'GK', 'NORDFELDT'),
  ('SWE', 24, 'DF', 'STROUD'),
  ('SWE', 25, 'FW', 'NILSSON'),
  ('SWE', 26, 'FW', 'ALI'),
  ('SUI', 1, 'GK', 'KOBEL'),
  ('SUI', 2, 'DF', 'MUHEIM'),
  ('SUI', 3, 'DF', 'WIDMER'),
  ('SUI', 4, 'DF', 'ELVEDI'),
  ('SUI', 5, 'DF', 'AKANJI'),
  ('SUI', 6, 'MF', 'ZAKARIA'),
  ('SUI', 7, 'FW', 'EMBOLO'),
  ('SUI', 8, 'MF', 'FREULER'),
  ('SUI', 9, 'MF', 'MANZAMBI'),
  ('SUI', 10, 'MF', 'XHAKA'),
  ('SUI', 11, 'FW', 'NDOYE'),
  ('SUI', 12, 'GK', 'MVOGO'),
  ('SUI', 13, 'DF', 'RODRIGUEZ'),
  ('SUI', 14, 'MF', 'JASHARI'),
  ('SUI', 15, 'MF', 'SOW'),
  ('SUI', 16, 'FW', 'FASSNACHT'),
  ('SUI', 17, 'FW', 'VARGAS'),
  ('SUI', 18, 'DF', 'CÖMERT'),
  ('SUI', 19, 'FW', 'OKAFOR'),
  ('SUI', 20, 'MF', 'AEBISCHER'),
  ('SUI', 21, 'GK', 'KELLER'),
  ('SUI', 22, 'MF', 'RIEDER'),
  ('SUI', 23, 'FW', 'AMDOUNI'),
  ('SUI', 24, 'DF', 'AMENDA'),
  ('SUI', 25, 'DF', 'JAQUEZ'),
  ('SUI', 26, 'FW', 'ITTEN'),
  ('TUN', 1, 'GK', 'CHAMAKH'),
  ('TUN', 2, 'DF', 'ABDI'),
  ('TUN', 3, 'DF', 'TALBI'),
  ('TUN', 4, 'DF', 'REKIK'),
  ('TUN', 5, 'DF', 'AROUS'),
  ('TUN', 6, 'DF', 'BRONN'),
  ('TUN', 7, 'FW', 'ACHOURI'),
  ('TUN', 8, 'FW', 'SAAD'),
  ('TUN', 9, 'FW', 'MASTOURI'),
  ('TUN', 10, 'MF', 'HANNIBAL'),
  ('TUN', 11, 'MF', 'GHARBI'),
  ('TUN', 12, 'DF', 'BEN OUANES'),
  ('TUN', 13, 'MF', 'KHEDIRA'),
  ('TUN', 14, 'MF', 'AYARI'),
  ('TUN', 15, 'MF', 'HADJ MAHMOUD'),
  ('TUN', 16, 'GK', 'DAHMEN'),
  ('TUN', 17, 'MF', 'SKHIRI'),
  ('TUN', 18, 'FW', 'ELLOUMI'),
  ('TUN', 19, 'FW', 'CHAOUAT'),
  ('TUN', 20, 'DF', 'VALERY'),
  ('TUN', 21, 'DF', 'BEN HMIDA'),
  ('TUN', 22, 'GK', 'BEN HESSEN'),
  ('TUN', 23, 'DF', 'NEFFATI'),
  ('TUN', 24, 'DF', 'CHIKHAOUI'),
  ('TUN', 25, 'MF', 'SLIMANE'),
  ('TUN', 26, 'MF', 'TOUNEKTI'),
  ('TUR', 1, 'GK', 'MERT'),
  ('TUR', 2, 'DF', 'ZEKİ ÇELİK'),
  ('TUR', 3, 'DF', 'DEMİRAL'),
  ('TUR', 4, 'DF', 'ÇAĞLAR'),
  ('TUR', 5, 'MF', 'ÖZCAN'),
  ('TUR', 6, 'MF', 'ORKUN KÖKÇÜ'),
  ('TUR', 7, 'FW', 'AKTÜRKOĞLU'),
  ('TUR', 8, 'FW', 'ARDA GÜLER'),
  ('TUR', 9, 'FW', 'DENİZ GÜL'),
  ('TUR', 10, 'MF', 'ÇALHANOĞLU'),
  ('TUR', 11, 'FW', 'YILDIZ'),
  ('TUR', 12, 'GK', 'ALTAY'),
  ('TUR', 13, 'DF', 'EREN ELMALI'),
  ('TUR', 14, 'DF', 'ABDÜLKERİM'),
  ('TUR', 15, 'DF', 'OZAN KABAK'),
  ('TUR', 16, 'MF', 'İSMAİL'),
  ('TUR', 17, 'FW', 'KAHVECİ'),
  ('TUR', 18, 'DF', 'MERT MÜLDÜR'),
  ('TUR', 19, 'FW', 'YUNUS'),
  ('TUR', 20, 'DF', 'F. KADIOĞLU'),
  ('TUR', 21, 'FW', 'BARIŞ'),
  ('TUR', 22, 'MF', 'KAAN'),
  ('TUR', 23, 'GK', 'UĞURCAN'),
  ('TUR', 24, 'FW', 'OĞUZ'),
  ('TUR', 25, 'DF', 'SAMET AKAYDIN'),
  ('TUR', 26, 'FW', 'CAN UZUN'),
  ('USA', 1, 'GK', 'TURNER'),
  ('USA', 2, 'DF', 'DEST'),
  ('USA', 3, 'DF', 'RICHARDS'),
  ('USA', 4, 'MF', 'ADAMS'),
  ('USA', 5, 'DF', 'A. ROBINSON'),
  ('USA', 6, 'DF', 'TRUSTY'),
  ('USA', 7, 'MF', 'REYNA'),
  ('USA', 8, 'MF', 'MCKENNIE'),
  ('USA', 9, 'FW', 'PEPI'),
  ('USA', 10, 'FW', 'PULISIC'),
  ('USA', 11, 'FW', 'AARONSON'),
  ('USA', 12, 'DF', 'M. ROBINSON'),
  ('USA', 13, 'DF', 'REAM'),
  ('USA', 14, 'MF', 'BERHALTER'),
  ('USA', 15, 'MF', 'ROLDAN'),
  ('USA', 16, 'DF', 'FREEMAN'),
  ('USA', 17, 'MF', 'TILLMAN'),
  ('USA', 18, 'DF', 'ARFSTEN'),
  ('USA', 19, 'FW', 'WRIGHT'),
  ('USA', 20, 'FW', 'BALOGUN'),
  ('USA', 21, 'FW', 'WEAH'),
  ('USA', 22, 'DF', 'MCKENZIE'),
  ('USA', 23, 'DF', 'SCALLY'),
  ('USA', 24, 'GK', 'FREESE'),
  ('USA', 25, 'GK', 'BRADY'),
  ('USA', 26, 'FW', 'ZENDEJAS'),
  ('URU', 1, 'GK', 'S. ROCHET'),
  ('URU', 2, 'DF', 'J.M. GIMÉNEZ'),
  ('URU', 3, 'DF', 'S. CACERES'),
  ('URU', 4, 'DF', 'R. ARAUJO'),
  ('URU', 5, 'MF', 'M. UGARTE'),
  ('URU', 6, 'MF', 'R. BENTANCUR'),
  ('URU', 7, 'MF', 'N. DE LA CRUZ'),
  ('URU', 8, 'MF', 'F. VALVERDE'),
  ('URU', 9, 'FW', 'D. NUÑEZ'),
  ('URU', 10, 'MF', 'G. DE ARRASCAETA'),
  ('URU', 11, 'FW', 'F. PELLISTRI'),
  ('URU', 12, 'GK', 'S. MELE'),
  ('URU', 13, 'DF', 'G. VARELA'),
  ('URU', 14, 'MF', 'A. CANOBBIO'),
  ('URU', 15, 'MF', 'E. MARTINEZ'),
  ('URU', 16, 'DF', 'M. OLIVERA'),
  ('URU', 17, 'DF', 'M. VIÑA'),
  ('URU', 18, 'FW', 'B. RODRIGUEZ'),
  ('URU', 19, 'FW', 'R. AGUIRRE'),
  ('URU', 20, 'MF', 'M. ARAUJO'),
  ('URU', 21, 'FW', 'F. VIÑAS'),
  ('URU', 22, 'MF', 'J. PIQUEREZ'),
  ('URU', 23, 'GK', 'F. MUSLERA'),
  ('URU', 24, 'DF', 'S. BUENO'),
  ('URU', 25, 'MF', 'J.M. SANABRIA'),
  ('URU', 26, 'MF', 'R. ZALAZAR'),
  ('UZB', 1, 'GK', 'YUSUPOV'),
  ('UZB', 2, 'DF', 'KHUSANOV'),
  ('UZB', 3, 'DF', 'ALIJONOV'),
  ('UZB', 4, 'DF', 'SAYFIEV'),
  ('UZB', 5, 'DF', 'ASHURMATOV'),
  ('UZB', 6, 'MF', 'MOZGOVOY'),
  ('UZB', 7, 'MF', 'SHUKUROV'),
  ('UZB', 8, 'MF', 'ISKANDEROV'),
  ('UZB', 9, 'MF', 'XAMROBEKOV'),
  ('UZB', 10, 'MF', 'JIYANOV'),
  ('UZB', 11, 'MF', 'URUNOV'),
  ('UZB', 12, 'GK', 'NEMATOV'),
  ('UZB', 13, 'DF', 'NASRULLAEV'),
  ('UZB', 14, 'FW', 'SHOMURODOV'),
  ('UZB', 15, 'DF', 'ESHMURODOV'),
  ('UZB', 16, 'GK', 'ERGASHEV'),
  ('UZB', 17, 'MF', 'KHAMDAMOV'),
  ('UZB', 18, 'DF', 'ABDULLAEV'),
  ('UZB', 19, 'MF', 'GANIEV'),
  ('UZB', 20, 'FW', 'AMONOV'),
  ('UZB', 21, 'FW', 'SERGEEV'),
  ('UZB', 22, 'MF', 'FAYZULLAEV'),
  ('UZB', 23, 'MF', 'ESANOV'),
  ('UZB', 24, 'DF', 'KARIMOV'),
  ('UZB', 25, 'DF', 'ULMASALIYEV'),
  ('UZB', 26, 'DF', 'UROZOV')
on conflict (team_code, name) do update
  set shirt_number = excluded.shirt_number, position = excluded.position;
